name: Github Actions Workflow
on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo stuff
        run: |
          pwd
          ls -a
          echo $CC_SECRET
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
